split_sector_columns = [
    "Number",
    "Name",
    "Run",
    "Speed",
    "Speed_Rank",
    "Orig_Split_1_Time",
    "Orig_Split_2_Time",
    "Orig_Split_3_Time",
    "Orig_Split_4_Time",
    "Orig_Split_5_Time",
    "Split_1_Rank",
    "Split_2_Rank",
    "Split_3_Rank",
    "Split_4_Rank",
    "Split_5_Rank",
    "Sector_1_Time",
    "Sector_2_Time",
    "Sector_3_Time",
    "Sector_4_Time",
    "Sector_5_Time",
    "Sector_1_Rank",
    "Sector_2_Rank",
    "Sector_3_Rank",
    "Sector_4_Rank",
    "Sector_5_Rank",
    "Cumulative_from_Split_1_Time",
    "Cumulative_from_Split_2_Time",
    "Cumulative_from_Split_3_Time",
    "Cumulative_from_Split_4_Time",
    "Cumulative_from_Split_1_Rank",
    "Cumulative_from_Split_2_Rank",
    "Cumulative_from_Split_3_Rank",
    "Cumulative_from_Split_4_Rank"
]

timedelta_columns = [
    "Orig_Split_1_Time",
    "Orig_Split_2_Time",
    "Orig_Split_3_Time",
    "Orig_Split_4_Time",
    "Orig_Split_5_Time",
    "Sector_1_Time",
    "Sector_2_Time",
    "Sector_3_Time",
    "Sector_4_Time",
    "Sector_5_Time",
    "Cumulative_from_Split_1_Time",
    "Cumulative_from_Split_2_Time",
    "Cumulative_from_Split_3_Time",
    "Cumulative_from_Split_4_Time"
]

# Explicitly list preferred columns in the desired order
preferred_columns = split_sector_columns
